const admin = [
  {
    id: 1,
    first_name: "Sumit",
    email: "admin@example.com",
    password: "123",
  },
];

const employees = [
  {
    id: 1,
    first_name: "Rajesh",
    email: "e@e.com",
    password: "123",
    task_count: {
      active: 2,
      new: 1,
      complete: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new: true,
        complete: false,
        failed: false,
        title: "Design Homepage",
        description: "Create a responsive design for the homepage.",
        date: "2024-10-05",
        category: "Design",
      },
      {
        active: false,
        new: false,
        complete: true,
        failed: false,
        title: "Update User Profiles",
        description: "Implement new fields in user profile section.",
        date: "2024-09-28",
        category: "Development",
      },
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "Market Analysis",
        description: "Analyze market trends for Q4.",
        date: "2024-10-10",
        category: "Marketing",
      },
    ],
  },
  {
    id: 2,
    first_name: "Anjali",
    email: "employee2@example.com",
    password: "123",
    task_count: {
      active: 2,
      new: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "Backend API Development",
        description: "Develop RESTful APIs for the mobile app.",
        date: "2024-10-12",
        category: "Development",
      },
      {
        active: false,
        new: false,
        complete: true,
        failed: false,
        title: "SEO Optimization",
        description: "Optimize website for search engines.",
        date: "2024-09-30",
        category: "Marketing",
      },
      {
        active: false,
        new: false,
        complete: false,
        failed: true,
        title: "Social Media Campaign",
        description: "Launch new campaign on social platforms.",
        date: "2024-10-08",
        category: "Marketing",
      },
      {
        active: true,
        new: true,
        complete: false,
        failed: false,
        title: "User Feedback Collection",
        description: "Gather feedback from users regarding new features.",
        date: "2024-10-15",
        category: "Customer Support",
      },
    ],
  },
  {
    id: 3,
    first_name: "Vikram",
    email: "employee3@example.com",
    password: "123",
    task_count: {
      active: 2,
      new: 1,
      complete: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "Content Creation",
        description: "Develop blog posts for the website.",
        date: "2024-10-07",
        category: "Content",
      },
      {
        active: true,
        new: true,
        complete: false,
        failed: false,
        title: "Email Marketing Setup",
        description: "Set up email marketing campaigns for new products.",
        date: "2024-10-20",
        category: "Marketing",
      },
      {
        active: false,
        new: false,
        complete: true,
        failed: false,
        title: "Graphic Design Update",
        description: "Refresh graphics for the mobile application.",
        date: "2024-09-25",
        category: "Design",
      },
    ],
  },
  {
    id: 4,
    first_name: "Priya",
    email: "employee4@example.com",
    password: "123",
    task_count: {
      active: 2,
      new: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new: true,
        complete: false,
        failed: false,
        title: "Database Migration",
        description: "Migrate database to the new server.",
        date: "2024-10-18",
        category: "Development",
      },
      {
        active: false,
        new: false,
        complete: true,
        failed: false,
        title: "Customer Support Training",
        description: "Train support team on new ticketing system.",
        date: "2024-09-20",
        category: "Customer Support",
      },
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "Product Launch Planning",
        description: "Plan the launch event for the new product.",
        date: "2024-10-25",
        category: "Marketing",
      },
      {
        active: false,
        new: false,
        complete: false,
        failed: true,
        title: "Bug Fixing",
        description: "Resolve reported bugs from the last release.",
        date: "2024-10-02",
        category: "Development",
      },
    ],
  },
  {
    id: 5,
    first_name: "Sneha",
    email: "employee5@example.com",
    password: "123",
    task_count: {
      active: 3,
      new: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "UI/UX Review",
        description: "Conduct a review of the current UI/UX design.",
        date: "2024-10-09",
        category: "Design",
      },
      {
        active: true,
        new: true,
        complete: false,
        failed: false,
        title: "Analytics Setup",
        description: "Set up Google Analytics for the website.",
        date: "2024-10-14",
        category: "Development",
      },
      {
        active: false,
        new: false,
        complete: true,
        failed: false,
        title: "Newsletter Distribution",
        description: "Send out monthly newsletters to subscribers.",
        date: "2024-09-22",
        category: "Marketing",
      },
      {
        active: false,
        new: false,
        complete: false,
        failed: true,
        title: "Server Maintenance",
        description: "Perform routine maintenance on the servers.",
        date: "2024-10-03",
        category: "IT",
      },
      {
        active: true,
        new: false,
        complete: false,
        failed: false,
        title: "Feature Testing",
        description: "Test new features before deployment.",
        date: "2024-10-19",
        category: "Quality Assurance",
      },
    ],
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
